-- ADDED INDEXING ONLY TWO COLUMNS THAT ARE BEING USED IN ONE OR MORE OPERATIONS 
-- (FOR INSTANCE: ACCESSING A ROW, SEARCHING FOR A VALUE ETC.)

-- TIME IMPROVEMENT FOR ALL THE QUERIES HAS BEEN REGISTERED IN THE 'Q3 - QUERY PLANS' FOLDER.

-- SCRIPTS FOR CREATING INDEXES ARE GIVEN BELOW:

CREATE INDEX type_index ON Title(type);
CREATE INDEX startYear_index ON Title(startYear);
CREATE INDEX endYear_index ON Title(endYear);
CREATE INDEX runtime_index ON Title(runtime);

CREATE INDEX name_index ON Member(name);
CREATE INDEX deathYear_index ON Member(deathYear);

CREATE INDEX character_index ON Character(character);

-- INDEX FOR PRIMARY KEY COLUMN(S) IS CREATED AUTOMATICALLY.

-- CREATING AN INDEX ELIMINATES THE NEED TO SCAN THE WHOLE TABLE FOR LOOKING UP A VALUE AND THUS
-- IMPROVES THE EXECUTION TIMES.